"""
test-gen/json_to_playwright.py
Converts a validated test_plan.json into an executable Playwright test file.

Usage:
    python json_to_playwright.py test_plan.json --out ../executor/generated_tests.py
"""
import argparse
import json

ACTION_TEMPLATES = {
    "goto": 'page.goto("{value}")',
    "click": 'page.click("{selector}")',
    "fill": 'page.fill("{selector}", "{value}")',
    "select": 'page.select_option("{selector}", "{value}")',
    "assert_visible": 'expect(page.locator("{selector}")).to_be_visible()',
    "assert_text": 'expect(page.locator("{selector}")).to_contain_text("{expected}")',
    "assert_status": "# status assertions handled via response listener, see executor",
    "wait_for": 'page.wait_for_selector("{selector}")',
}


def step_to_code(step: dict) -> str:
    template = ACTION_TEMPLATES.get(step["action"])
    if not template:
        return f"# unsupported action: {step['action']}"
    return "    " + template.format(
        selector=step.get("selector", ""),
        value=step.get("value", ""),
        expected=step.get("expected", ""),
    )


def scenario_to_test_function(scenario: dict) -> str:
    fn_name = f"test_{scenario['id'].lower().replace('-', '_')}"
    lines = [
        f"def {fn_name}(page):",
        f'    """{scenario["title"]} | priority={scenario["priority"]} | type={scenario["type"]}"""',
        f"    scenario_id = '{scenario['id']}'",
        f"    fallback_selectors = {scenario.get('fallback_selectors', [])}",
    ]
    for step in scenario["steps"]:
        try:
            lines.append(step_to_code(step))
        except KeyError as e:
            lines.append(f"    # skipped malformed step, missing {e}")
    lines.append("")
    return "\n".join(lines)


def build_file(test_plan: dict) -> str:
    header = (
        "# AUTO-GENERATED by test-gen/json_to_playwright.py — do not hand-edit.\n"
        "# Re-run the generator if the test plan changes.\n"
        "from playwright.sync_api import expect\n\n"
    )
    functions = [scenario_to_test_function(s) for s in test_plan["scenarios"]]
    return header + "\n".join(functions)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("test_plan_file")
    parser.add_argument("--out", default="generated_tests.py")
    args = parser.parse_args()

    with open(args.test_plan_file) as f:
        test_plan = json.load(f)

    code = build_file(test_plan)

    with open(args.out, "w") as f:
        f.write(code)

    print(f"{len(test_plan['scenarios'])} test functions written to {args.out}")